# Generated by Django 3.0.5 on 2020-04-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('level1', 'Level 1'), ('level2', 'Level 2'), ('admin', 'Admin')], default='level1', max_length=50),
        ),
    ]
