# Generated by Django 3.0.5 on 2020-04-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200424_0512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(max_length=150, verbose_name='Vimeo ID only')),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('day', models.CharField(max_length=50)),
            ],
        ),
    ]
