# Generated by Django 3.0.5 on 2020-07-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200515_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='video',
            name='role',
            field=models.CharField(choices=[('level1', 'Level 1'), ('level2', 'Level 2'), ('admin', 'Admin')], default='level1', max_length=50),
            preserve_default=False,
        ),
    ]
