# Generated by Django 3.0.5 on 2020-09-28 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200928_0500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='program',
        ),
    ]
