# Generated by Django 3.0.5 on 2020-09-28 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_video_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Program'),
            preserve_default=False,
        ),
    ]
