# Generated by Django 3.0.5 on 2020-09-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_video_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='role',
            field=models.CharField(blank=True, choices=[('level1', 'Level 1'), ('level2', 'Level 2'), ('level3', 'Level 3'), ('admin', 'Admin')], max_length=50, null=True),
        ),
    ]
