# Generated by Django 3.0.5 on 2020-10-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20200928_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='role',
            field=models.CharField(blank=True, default='level1', max_length=50),
            preserve_default=False,
        ),
    ]
