# Generated by Django 3.0.5 on 2020-12-17 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20201001_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(max_length=150, verbose_name='Vimeo ID only')),
                ('assetType', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], default='audio', max_length=50)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('day', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('role', models.CharField(choices=[('level1', 'Level 1'), ('level2', 'Level 2'), ('level3', 'Level 3'), ('admin', 'Admin')], max_length=50)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Program')),
            ],
            options={
                'ordering': ['day'],
            },
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
