# Generated by Django 3.0.5 on 2021-08-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20210820_0558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='program',
            name='role',
        ),
        migrations.AddField(
            model_name='category',
            name='role',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
